on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        python-version: [ "3.8", "3.12" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - name: install dependencies
        run: pip install -r requirements-dev.txt
      - name: ruff check
        run: python -m ruff check
      - name: test with coverage
        run: python -m pytest
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: ${{ matrix.python-version == '3.12' }}